### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by deeptiantony** [zolyfarkas/avro#10]
I checked out the code from release tag avro-toplevel-1.10.0.9p, and was trying the build the project under lang/java/avro. However it fails with below exception 
[ERROR] Failed to execute goal on project avro: Could not resolve dependencies for project org.apache.avro:avro:bundle:1.10.0.9p: The following artifacts could not be resolved: org.spf4j.avro:core-schema:jar:0.19, org.apache.avro:avro:jar:1.10.0.2p: Could not find artifact org.spf4j.avro:core-schema:jar:0.19 in github (https://api.github.com/users/zolyfarkas/repos/*) -> [Help 1]
[ERROR]

core-schema:jar:0.19, seems unavailable in maven repository as well.

**Comment by zolyfarkas** [comment]
Thanks for reporting this, some of the unit tests depend on that artifact that used to be hosted on bin-tray.
Will upload an update that depends on artifacts from maven central.

**Comment by zolyfarkas** [comment]
Uploaded fix in latest snapshot. Let me know if it works or not. thanks!

**Comment by deeptiantony** [comment]
I could not find any branch/tag recently updated. @zolyfarkas  Can you tell me which one has the fix?

**Comment by zolyfarkas** [comment]
Sorry about that, the push was imaginary :-)

here is the change after O actually made it: https://github.com/zolyfarkas/avro/commit/6bdd2ce2e766967a2533c2d1a64b63ee491697d3

**Comment by deeptiantony** [comment]
Thank you.. Then, I was facing the below issue
[ERROR] Failed to execute goal on project avro: Could not resolve dependencies for project org.apache.avro:avro:bundle:1.10.0.10p-SNAPSHOT: Could not find artifact org.apache.avro:avro:jar:1.10.0.2p in github (https://api.github.com/users/zolyfarkas/repos/*) -> [Help 1]

But somehow was able to fix it by adding dependency. 

@zolyfarkas - Is there any expected date to release for Apache Avro version 1.10.1 ?

**Comment by zolyfarkas** [comment]
I can do a release anytime.

this dependency fix is the only issue that would be included, so I don’t see it right now as a high priority to do a release.
A bug or feature can change that easily, and I usually do a release as soon as I have something something like that.

current release is 

avro-toplevel-1.10.0.9p  <https://github.com/zolyfarkas/avro/releases/tag/avro-toplevel-1.10.0.9p>

next release should be:
avro-toplevel-1.10.0.10p  <https://github.com/zolyfarkas/avro/releases/tag/avro-toplevel-1.10.0.9p>

unless there is something major in it.

—Z
