### ISSUE TITLE
Support for Avro 1.11

### ISSUE THREAD

**Issue by philipp94831** [zolyfarkas/avro#11]
Hi, do you have any plans for supporting Avro 1.11?

**Comment by zolyfarkas** [comment]
Yes, what specific feature in  1.11 are you interested in?

—Z

**Comment by zolyfarkas** [comment]
published 1.10.0.12p which resolves one compatibility issues with latest avro, give it a try. Please report error details if you encounter any.

thank you.

**Comment by philipp94831** [comment]
Seems to be working. Thanks!
