### ISSUE TITLE
Bintray is going away, any plans to publish the binary somewhere else?

### ISSUE THREAD

**Issue by jivko16** [zolyfarkas/avro#6]
Based on this article, Bintray is going away on May.1st.2021 and will no longer serve the binary for this project.
Do you have plans for moving the binary somewhere else, if yes, what's your timeframe.
Any recommendations of how to proceed with this after May 1st for projects that depends on the project?

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by ahirata** [comment]
Hi @zolyfarkas, do you have any news on this? We are depending on this fork too and want to plan our options.

**Comment by zolyfarkas** [comment]
Hi, sorry for the late reply, I will try to migrate to github packages to be able to maintain the groupId/artifactId.
If that is unpractical, I will migrate to sonatype, just like all my other projects. For that though I will change the group id of the libraries to org.spf4j.org.apache

**Comment by zolyfarkas** [comment]
I have published, 1.10.0.1p to github packages, updated the README file  with details. Currently I have no plans to migrate any old packages to github pages, and I think they will be still available on bintray until FEB 2022. 
Please give it a try and let me know if you see any issues.
If anyone needs any old versions to bemigrated to github packages I can make them available, but please consider using the latest version first.

**Comment by ahirata** [comment]
Hi @zolyfarkas, we upgraded to `1.10.0.1p` and I can confirm it's working as intended.

Thank you!

**Comment by zolyfarkas** [comment]
Awesome!

**Comment by matJC** [comment]
> I have published, 1.10.0.1p to github packages, updated the README file with details. Currently I have no plans to migrate any old packages to github pages, and I think they will be still available on bintray until FEB 2022.
> Please give it a try and let me know if you see any issues.
> If anyone needs any old versions to bemigrated to github packages I can make them available, but please consider using the latest version first.

The older packages are in fact not available from bintray at this point.

**Comment by zolyfarkas** [comment]
I highly recommend moving away from the older packages, they have security vulnerabilities. At this point I see not incentive to re-publish them.
