### ISSUE TITLE
Unauthorized or forbidden for install

### ISSUE THREAD

**Issue by jasondavindev** [zolyfarkas/avro#7]
I was using this dependecy on my project and now I''m receiving the error below:
```
Authorization failed for https://dl.bintray.com/zolyfarkas/core/org/apache/avro/avro/1.8.1.48p/avro-1.8.1.48p.pom 403 Forbidden
```

I tried upgrade to new link, using github link but now I'm receiving an another error 401 - unauthorized.
```
Authentication failed for https://maven.pkg.github.com/zolyfarkas/*/org/apache/avro/avro/1.10.0.1p/avro-1.10.0.1p.pom 401 Unauthorized
```
Can help me?

**Comment by zolyfarkas** [comment]
Sure, 

you will need to authenticate to github packages. see https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry <https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry> 

add in your settings.xml:

    <server>
      <id>github.com</id>
      <username>yourusername</username>
      <password>yourauthenticationtoken</password>
    </server>

hopefully github will remove the authentication requirements soon...


—Z

**Comment by jasondavindev** [comment]
My build and deploy is made from the Circleci

**Comment by zolyfarkas** [comment]
For an example of how to set this up in a Travis CI, see: https://github.com/zolyfarkas/spf4j/.travis.* files.

The same thing you will need to do in any CI system (like Jenkins, etc)

**Comment by jasondavindev** [comment]
I created a token on github and included in the environment variables from my circleci workflow.
Thanks!
